### ISSUE TITLE
iOS SDK doesn't support upToDate dataCallback parameter. 

### ISSUE THREAD

**Issue by viktorVlakh** [ChartIQ/ChartIQ-iOS-SDK#33]
I am rendering chart in `pull` mode (chartIQ call pullPaginationData with `start` and `end` date parameters, we returns an array of candles). 

Sometimes it continues nonstop calling  `pullPaginationData` with the same date range `from`  - `now`. 
According to the [documentation](https://documentation.chartiq.com/quotefeed.html#main) to stop this cycle we need set `upToDate` paramter.  But getScriptForFormatJSQuoteData doesn't support it

`getScriptForFormatJSQuoteData(_ json: String, moreAvailable: Bool, cb: String) -> String` 

**Actual result**
Endless loop

**Comment by jdrichards50** [comment]
@viktorVlakh, thanks for pointing this out. This is scheduled to be part of our next release. In the meantime, if you are using ChartIQ version 8.4 the endless quotefeed loop should no longer happen. You can also add the `upToDate` flag manually to the quotefeed callback in the `parseData` function in **nativeSdkBridge.js**. 

Also, we don't normally check Github issues. So in the future please send your questions to support@chartiq.com for a more prompt response. 

Thanks!

**Comment by viktorVlakh** [comment]
Got it. Thank you.
