### ISSUE TITLE
Facing issue while implementing chartIQ_8.9.0 library I iOS application

### ISSUE THREAD

**Issue by BhagyashriMo** [ChartIQ/ChartIQ-iOS-SDK#46]
Hello,
I am getting this issue after sending script "CIQ.MobileBridge.loadChart(\"360 ONE WAM Ltd(360ONE)-NSE\");"

Printing description of error:
▿ Optional<Error>
  - some : Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: CIQ, WKJavaScriptExceptionColumnNumber=4, WKJavaScriptExceptionSourceURL, NSLocalizedDescription=A JavaScript exception occurred}
  
  Please help me out for this issue. I am getting stuck and unable to load chart candle.

**Comment by yorkmoy** [comment]
Hello BhagyashriMo!
If you are an existing ChartIQ Charting Library client, please contact us at support@chartiq.com . Our developers will be happy to work with you.

Note that ChartIQ-iOS-SDK requires a copy of the ChartIQ Charting SDK. If you haven't already done so, please request a copy from this form, https://pages.marketintelligence.spglobal.com/ChartIQ-free-trial-request.html .

Thank for reaching out to us!

**Comment by BhagyashriMo** [comment]
Hello yorkmoy,
Yes I will. Thanks for your response.
